const leaders = [{
    "name": "Joe Burrow",
    "team": "Bengals",
    "yards": 1781,
    "tds": 11,
    "ints": 20,
    "completion": 57,
    "rushing": 21,
    "rushingTds": 1,
    "rank": 1,
    "votes": 0,
}, {
    "name": "Justin Herbert",
    "team": "Chargers",
    "yards": 1770,
    "tds": 13,
    "ints": 9,
    "completion": 76,
    "rushing": 22,
    "rushingTds": 1,
    "rank": 2,
    "votes": 0,
}, {
    "name": "Tua Tagovailoa",
    "team": "Chargers",
    "yards": 1770,
    "tds": 13,
    "ints": 9,
    "completion": 76,
    "rushing": 22,
    "rushingTds": 1,
    "rank": 2,
    "votes": 0,
}]